# Generated by Django 3.2.8 on 2022-03-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishmartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200, null=True)),
                ('weight', models.IntegerField(max_length=200, null=True)),
                ('price', models.IntegerField(max_length=200, null=True)),
                ('photo', models.ImageField(default=0, upload_to='image')),
            ],
        ),
    ]
