# Generated by Django 3.2.8 on 2022-03-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishmartapp', '0002_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
