# Generated by Django 3.2.8 on 2022-03-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishmartapp', '0003_alter_productdb_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
