# Generated by Django 3.2.8 on 2022-03-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishmartapp', '0004_productdb_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
