# Generated by Django 3.2.8 on 2022-03-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=200, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('Subject', models.CharField(max_length=200, null=True)),
                ('Message', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
