# Generated by Django 3.2.8 on 2022-03-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdb',
            old_name='Email',
            new_name='email',
        ),
    ]
