# Generated by Django 3.2.8 on 2022-03-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0004_cartdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartdb',
        ),
    ]
