# Generated by Django 3.2.8 on 2022-03-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishmartapp', '0005_alter_productdb_weight'),
        ('martapp', '0005_delete_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('productid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishmartapp.productdb')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='martapp.registerdb')),
            ],
        ),
    ]
